import type { Metadata } from "next";
import { Libre_Baskerville } from "next/font/google";
import "./globals.css";
import { poker } from "@/components/custom-fonts";
import { ClerkProvider } from "@clerk/nextjs";
import Nav from "@/components/nav";
import { ThemeProvider } from "@/providers/theme-provider";
const Baskerville = Libre_Baskerville({
  subsets: ["latin", "latin-ext"],
  weight: ["400", "700"],
  variable: "--font-baskerville",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` ${Baskerville.variable} ${poker.variable}   w-screen flex justify-center bg-background `}
    >
      <body
        className={`  w-full max-w-[1440px] flex justify-center flex-col  `}
      >
        <ClerkProvider
          appearance={{
            variables: { colorPrimary: "#7Ed348" },
          }}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Nav />
            {children}
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
